2025-03-21 03:46:45,815 - INFO - Starting background task
2025-03-21 03:46:45,815 - ERROR - Background task error: I/O operation on closed file
2025-03-21 03:47:08,018 - INFO - Starting background task
2025-03-21 03:47:08,018 - ERROR - Background task error: I/O operation on closed file
2025-03-21 03:48:08,018 - ERROR - Background task error: I/O operation on closed file
2025-03-21 03:49:08,021 - ERROR - Background task error: I/O operation on closed file
2025-03-21 03:50:08,023 - ERROR - Background task error: I/O operation on closed file
2025-03-21 03:51:08,025 - ERROR - Background task error: I/O operation on closed file
2025-03-21 03:52:08,030 - ERROR - Background task error: I/O operation on closed file
2025-03-21 03:53:08,032 - ERROR - Background task error: I/O operation on closed file
2025-03-21 03:54:08,036 - ERROR - Background task error: I/O operation on closed file
2025-03-21 03:55:08,043 - ERROR - Background task error: I/O operation on closed file
2025-03-21 03:56:08,047 - ERROR - Background task error: I/O operation on closed file
2025-03-21 03:57:08,053 - ERROR - Background task error: I/O operation on closed file
2025-03-21 03:58:08,056 - ERROR - Background task error: I/O operation on closed file
2025-03-21 03:59:08,058 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:00:08,061 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:01:08,063 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:02:08,067 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:03:08,071 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:04:08,074 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:05:08,076 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:06:08,078 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:07:08,067 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:08:08,070 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:09:08,073 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:10:08,074 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:11:08,075 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:12:08,076 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:13:08,077 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:14:08,082 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:14:50,898 - INFO - Starting background task
2025-03-21 04:14:50,898 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:15:13,326 - INFO - Starting background task
2025-03-21 04:15:13,326 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:15:29,403 - INFO - Starting background task
2025-03-21 04:15:29,403 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:15:45,042 - INFO - Starting background task
2025-03-21 04:15:45,042 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:16:02,005 - INFO - Starting background task
2025-03-21 04:16:02,005 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:17:02,008 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:18:02,012 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:19:02,019 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:20:02,021 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:21:02,024 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:22:02,027 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:24:11,354 - INFO - Starting background task
2025-03-21 04:24:11,354 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:25:11,356 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:26:11,358 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:27:11,359 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:28:11,293 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:29:11,293 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:30:11,294 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:31:11,294 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:32:11,294 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:33:11,294 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:34:11,294 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:35:11,294 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:36:11,293 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:37:11,293 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:38:11,292 - ERROR - Background task error: I/O operation on closed file
2025-03-21 04:38:40,991 - INFO - Starting background task
2025-03-21 04:38:40,991 - ERROR - Background task error: module 'aiofiles' has no attribute 'os'
2025-03-21 04:39:11,718 - INFO - Starting background task
2025-03-21 04:39:11,719 - ERROR - Background task error: module 'aiofiles' has no attribute 'os'
2025-03-21 04:39:53,253 - INFO - Starting background task
2025-03-21 04:39:53,255 - ERROR - Background task error: module 'aiofiles' has no attribute 'os'
2025-03-21 04:40:53,257 - ERROR - Background task error: module 'aiofiles' has no attribute 'os'
2025-03-21 04:41:53,262 - ERROR - Background task error: module 'aiofiles' has no attribute 'os'
2025-03-21 04:42:53,270 - ERROR - Background task error: module 'aiofiles' has no attribute 'os'
2025-03-21 04:43:53,272 - ERROR - Background task error: module 'aiofiles' has no attribute 'os'
2025-03-21 04:45:10,577 - INFO - Starting background task
2025-03-21 05:25:02,851 - INFO - Starting background task
2025-03-21 05:25:11,969 - INFO - Starting background task
2025-03-21 19:15:57,316 - INFO - バックグラウンドタスク開始
2025-03-21 19:17:51,069 - INFO - Starting background task
2025-03-21 19:17:59,377 - INFO - Starting background task
2025-03-21 20:20:41,999 - INFO - Starting background task
2025-03-21 20:20:45,329 - INFO - Starting background task
2025-03-21 22:09:44,253 - INFO - Starting background task
2025-03-21 22:11:41,523 - ERROR - Toggl API Error: 400 "Since is expected to be an unix timestamp, integer value"
2025-03-21 22:11:54,917 - ERROR - Toggl API Error: 400 "Since is expected to be an unix timestamp, integer value"
2025-03-21 22:20:54,304 - INFO - Starting background task
2025-03-21 22:21:02,938 - WARNING - Invalid entry: 'NoneType' object is not subscriptable
2025-03-21 22:21:33,905 - WARNING - Invalid entry: 'NoneType' object is not subscriptable
2025-03-21 22:37:25,971 - INFO - 【自動切り忘れ機能】有効
2025-03-21 22:37:25,972 - INFO - 【自動切り忘れ機能】バックグラウンドタスク開始
2025-03-21 22:39:52,841 - WARNING - Invalid entry: 'NoneType' object is not subscriptable
2025-03-21 22:40:09,808 - ERROR - Project not found: システム開発
2025-03-21 22:41:41,156 - ERROR - Project not found: noproject
2025-03-21 22:50:55,462 - INFO - 【自動切り忘れ機能】有効
2025-03-21 22:50:55,462 - INFO - 【自動切り忘れ機能】バックグラウンドタスク開始
2025-03-21 22:50:55,654 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 22:50:55,849 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 22:51:26,062 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 22:51:26,261 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 22:51:40,750 - WARNING - Invalid entry: 'NoneType' object is not subscriptable
2025-03-21 22:52:36,899 - ERROR - Toggl API Error: 403 "workspace not found/accessible"
2025-03-21 22:52:36,901 - ERROR - Project not found: 1192
2025-03-21 22:53:58,125 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 22:53:58,330 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 22:54:28,533 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 22:54:28,734 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 22:54:58,947 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 22:54:59,142 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:18:41,313 - INFO - 【自動切り忘れ機能】有効
2025-03-21 23:18:41,313 - INFO - 【自動切り忘れ機能】バックグラウンドタスク開始
2025-03-21 23:18:59,845 - INFO - 【自動切り忘れ機能】有効
2025-03-21 23:18:59,845 - INFO - 【自動切り忘れ機能】バックグラウンドタスク開始
2025-03-21 23:22:36,148 - INFO - 【自動切り忘れ機能】有効
2025-03-21 23:22:36,148 - INFO - 【自動切り忘れ機能】バックグラウンドタスク開始
2025-03-21 23:48:59,691 - INFO - 【自動切り忘れ機能】有効
2025-03-21 23:48:59,692 - INFO - 【自動切り忘れ機能】バックグラウンドタスク開始
2025-03-21 23:48:59,898 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:49:00,098 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:49:30,309 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:49:30,512 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:50:00,724 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:50:00,921 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:50:31,139 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:50:31,337 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:51:01,548 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:51:01,748 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:51:31,954 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:51:32,155 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:52:02,381 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:52:02,577 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:52:32,795 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:52:32,997 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:53:03,199 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:53:03,394 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:53:33,603 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-21 23:53:33,806 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:01:42,937 - INFO - 【自動切り忘れ機能】有効
2025-03-22 00:01:42,938 - INFO - 【自動切り忘れ機能】バックグラウンドタスク開始
2025-03-22 00:01:47,271 - INFO - 【自動切り忘れ機能】有効
2025-03-22 00:01:47,271 - INFO - 【自動切り忘れ機能】バックグラウンドタスク開始
2025-03-22 00:01:53,840 - INFO - 【自動切り忘れ機能】有効
2025-03-22 00:01:53,841 - INFO - 【自動切り忘れ機能】バックグラウンドタスク開始
2025-03-22 00:01:54,044 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:01:54,244 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:02:24,456 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:02:24,657 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:02:39,546 - INFO - 【自動切り忘れ機能】有効
2025-03-22 00:02:39,547 - INFO - 【自動切り忘れ機能】バックグラウンドタスク開始
2025-03-22 00:02:39,746 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:02:39,944 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:02:47,000 - INFO - 【自動切り忘れ機能】有効
2025-03-22 00:02:47,000 - INFO - 【自動切り忘れ機能】バックグラウンドタスク開始
2025-03-22 00:02:53,969 - INFO - 【自動切り忘れ機能】有効
2025-03-22 00:02:53,969 - INFO - 【自動切り忘れ機能】バックグラウンドタスク開始
2025-03-22 00:02:54,166 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:02:54,361 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:03:24,581 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:03:24,776 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:03:54,982 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:03:55,182 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:04:21,810 - INFO - 【自動切り忘れ機能】有効
2025-03-22 00:04:21,810 - INFO - 【自動切り忘れ機能】バックグラウンドタスク開始
2025-03-22 00:04:22,012 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:04:22,206 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:04:48,828 - INFO - 【自動切り忘れ機能】有効
2025-03-22 00:04:48,828 - INFO - 【自動切り忘れ機能】バックグラウンドタスク開始
2025-03-22 00:04:49,031 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:04:49,229 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:23:38,143 - INFO - 【自動切り忘れ機能】有効
2025-03-22 00:23:38,143 - INFO - 【自動切り忘れ機能】バックグラウンドタスク開始
2025-03-22 00:23:38,344 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:23:38,541 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:24:08,749 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:24:08,946 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:24:39,155 - ERROR - User 723423987950157895 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
2025-03-22 00:24:39,359 - ERROR - User Ub8ffc32dfa36a4bd3f623f7cc56e7d92 check error: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
